server:
  port: 8080
spring:
  application:
    name: "HexagonBank"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:mysql://localhost:3306/production?serverTimezone=UTC"
    username: "root"
    password: "Queryheros10"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    databasePlatform: "org.hibernate.dialect.MySQLDialect"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/"
      database: "HexagonBankDB"
      username: "mongouser"
      password: "mongopass"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
